# Generated by Django 4.1.2 on 2022-10-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='facebook',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
