# Generated by Django 4.1.2 on 2022-10-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ui', '0002_alter_footer_facebook_alter_footer_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='copyright',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
