export const PRIMARY = '#EC67B1';
export const SECONDARY = '#333333';
export const NAV = '#554994';
export const DESCRIPTION = '#8E8E8E';
export const WHITE = '#FFFFFF';
export const SUCCESS = '#A2D17D'; //! Needs to be checked
export const WARNING = '#ffae00'; //! Needs to be checked
export const DANGER = '#d52c63'; //! Needs to be checked
export const LABEL = '#9FB2DC';
export const BLACK = '#180A0A';
export const BLUE = '#9FB2DC';
