# Generated by Django 4.1.2 on 2022-10-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
