# Generated by Django 4.1.2 on 2022-10-15 17:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutuspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ul'])), ('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True),
        ),
    ]
