# Generated by Django 4.1.2 on 2022-10-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_footerpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerpage',
            name='image',
        ),
    ]
