# Generated by Django 4.1.2 on 2022-10-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutuspage'),
        ('blog', '0005_remove_footerpage_image'),
    ]

    operations = [
    ]
